version: "3.8"
services:
  dps:
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - MG_LOG_LEVEL=ERROR
    hostname: dns.mageddo
    networks:
      dps:
        ipv4_address: 172.0.0.10
  my-apache:
    build: https://github.com/kit-data-manager/frontend-collection.git#docker-metastore
    image: my-apache
    ports:
     - "80:80"
    networks:
      - dps
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elastic4indexing
    environment:
      - discovery.type=single-node
#      - logger.org.elasticsearch=ERROR
      - HOSTNAMES=elastic.docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - dps
  rabbitmq:
    image: rabbitmq:3-management
    depends_on:
      - elasticsearch
    container_name: rabbitmq4indexing
    environment:
      - HOSTNAMES=rabbitmq.docker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dps
  indexing-service:
    image: kitdm/indexing-service:v0.1.3
    container_name: indexing4metastore
    depends_on:
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    ports:
      - "8050:8050"
    volumes:
      - ./settings/indexing-service:/spring/indexing-service/config
    networks:
      - dps
  metastore:
    image: kitdm/metastore2:v1.2.2
    container_name: metastore.docker
    environment:
      - HOSTNAMES=metastore.docker
    depends_on:
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    ports:
      - "8040:8040"
    volumes:
      - ./settings/metastore:/spring/metastore2/config
    networks:
      - dps
networks:
  dps:
    ipam:
      config:
        - subnet: 172.0.0.0/24
