version: "3.8"
services:
  dps:
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - MG_LOG_LEVEL=ERROR
    hostname: dns.mageddo
    networks:
      dps:
        ipv4_address: 172.0.0.10
  my-apache:
    image: ${PREFIX4DOCKER}/frontend-collection-metastore:${FRONTEND_COLLECTION_VERSION}
    container_name: my_apache
    ports:
     - "80:80"
    networks:
      - dps
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elastic.docker
    hostname: elastic.docker
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
#      - logger.org.elasticsearch=ERROR
      - HOSTNAMES=elastic.docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - dps
  rabbitmq:
    image: rabbitmq:4-management
    depends_on:
      - elasticsearch
    container_name: rabbitmq4indexing
    hostname: rabbitmq.docker
    environment:
      - HOSTNAMES=rabbitmq.docker
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dps
  indexing-service:
    image: ${PREFIX4DOCKER}/indexing-service:${INDEXING_SERVICE_VERSION}
    container_name: indexing4metastore
    environment:
      - REPO_MESSAGING_USERNAME=${RABBIT_MQ_USER}
      - REPO_MESSAGING_PASSWORD=${RABBIT_MQ_PASSWORD}
      - REPO_AUTH_JWTSECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    ports:
      - "8050:8050"
    volumes:
      - ./settings/indexing-service:/spring/indexing-service/config
    networks:
      - dps
  metastore:
    image: ${PREFIX4DOCKER}/metastore2:${METASTORE_VERSION}
    container_name: metastore.docker
    hostname: metastore.docker
    environment:
      - HOSTNAMES=metastore.docker
      - REPO_SEARCH_ENABLED=true
      - REPO_MESSAGING_ENABLED=true
      - REPO_MESSAGING_USERNAME=${RABBIT_MQ_USER}
      - REPO_MESSAGING_PASSWORD=${RABBIT_MQ_PASSWORD}
      - MANAGEMENT_HEALTH_RABBIT_ENABLED=true
      - REPO_AUTH_ENABLED=${REPO_AUTH_ENABLED}
      - REPO_AUTH_JWTSECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    ports:
      - "8040:8040"
    volumes:
      - ./settings/metastore:/spring/metastore2/config
    networks:
      - dps
networks:
  dps:
    ipam:
      config:
        - subnet: 172.0.0.0/24
