# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build docker image for tag

on:  
  push:
    tags:
      - '*'

env:
    # JDK version used for building jar file
    currentBuildVersion: 8
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up OpenJDK version ...
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' 
        java-version: ${{ env.currentBuildVersion }}
    - name: Create docker image and push it to docker hub with given tag
      run: echo ToDo...
