# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build with gradle

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
    # JDK version used for building jar file
    currentBuildVersion: 8
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use both LTS releases and latest one for tests
        jdk: [ 8, 11 ]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up OpenJDK version ...
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' 
        java-version: ${{ matrix.jdk }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Ptravis clean build jacocoTestReport
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up OpenJDK version ...
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' 
        java-version: ${{ env.currentBuildVersion }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle (JDK ${{ env.currentBuildVersion }})
      run: ./gradlew -Ptravis clean check jacocoTestReport
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./build/reports/jacoco/test/jacocoTestReport.xml #optional
  docker:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build docker and push it to docker hub ...
      run: echo ToDo....
